[workspace]
resolver = "3"

members = [
    "executables/referenceApp/rustHelloWorld",
]

[workspace.package]
version = "0.1.0"
documentation = "https://eclipse-openbsw.github.io/openbsw/"

# Workspace dependencies - add new Rust crates here as they are developed
[workspace.dependencies]

# Similar to C++ we always build optimized (matching C++ -O2)
[profile.dev]
panic = "abort"
lto = true
opt-level = 2
incremental = false
codegen-units = 1
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = 2
incremental = false
codegen-units = 1
debug = true
